'
# Assignment 2: Python Basics and GitHub Pages Website

For this assignment, see the QMD or IPYNB files in our course repository named 02-python_basics.qmd or 02-python_basics.ipynb.

Most things in this can be solved using methods shown in lecture. However, some cases will require you to search the internet for answers.


## Question 1

a). **Indentation and Pythonic Code**:
   - Create a function named `print_numbers` that prints numbers from 1 to 10, each on a new line. Ensure your code is properly indented and follows Pythonic conventions.

```{python}
#1 a) 
def print_numbers():
   """ Prints numbers from 1 to 10, each on a new line. """
   for i in range(1, 11):
      print(i)

```

b.) **Rules of Functions and Comments**:
   - Define a function named `calculate_area` that takes two arguments `length` and `width`, and returns the area of a rectangle. Include a docstring explaining what the function does. See the lecture notes for an example of a docstring.

```{python}
#1 b) 
def calculate_area(length, width):
   """Calculates the area of a rectangle. Takes two arguments `length` and `width`, and returns the area of a rectangle with those dimensions."""
   return(length * width)
```

c.) **Basic Data Types**:
   - Create a variable `is_active` and set it to `True`. Print the type of `is_active` using the `type()` function.

```{python}
#1 c) Answer:
is_active = True
type(is_active)
```

d.) **Working with Lists**:
   - Create a list named `fruits` containing some fruit names. Use the `append` method to add 'Mango' to the list and print the updated list.

```{python}
#1 d) Answer:
fruits = ["Banana", "Passionfruit", "Kiwi", "Lychee"]
fruits.append("Mango")
print(fruits)
```

## Question 2:
a.) **Naming Conventions**:
   - Create a variable following the snake_case naming convention to store the number of days in a week.

```{python}
#2 a) Answer: 
import calendar
days_in_a_week = len(calendar.day_name)
print(days_in_a_week)
```

b.) **Control Flows - Conditionals**:
   - Write a simple program that checks if a number is positive, negative, or zero using `if`, `elif`, and `else` statements.

```{python}
#2 b) Answer:
import math
i = math.pi

if i == 0:
   print(i, " equals zero.")
elif i < 0:
   print(i, " is negative.")
else:
   print(i, " is positive.")
```

c.) **Control Flows - Loops**:
   - Write a `for` loop to calculate the sum of numbers from 1 to 100.

```{python}
#2 c) Answer:
n = 0
for i in range(0, 101):
   n += i
print(n)
```

d.) **Control Flows - Loop Control Statements**:
   - Modify the loop from the previous sub-question to stop the loop if the sum becomes greater than 1000 using a `break` statement.

```{python}
#2 c) Answer: 
n = 0
for i in range(0, 101):
   n += i
   if n > 1000:
      break
print(n)
```

e.) **Functions - Arguments and Return Values**:
   - Create a function named `get_full_name` that takes two arguments `first_name` and `last_name`, and returns the full name.

```{python}
#2 e) Answer:
def get_full_name(first_name, last_name):
   """Takes two arguments `first_name` and `last_name`, and returns the full name on one line."""
   print(f"{first_name} {last_name}")
```

## Question 3
**Part A:** Write a python function that calculates the sum of all squared 
numbers from 1 to x. Illustrate that it works for x = 20.

HINT, ** is the exponent operator in python.
HINT syntax for a python function is:

def function_name(variable_name):
    outcome = variable_name + 1
    return outcome

```{python}
#3A Answer

def sum_squares_until(x: int) -> int:  #Ensures input and output are integers
   """Calculates the sum of all squared integers from 1 to x. Takes an input positive integer x and ouputs an integer."""
   sum_squares = 0
   for i in range(1, x+1):
      sum_squares += i**2
   return sum_squares

sum_squares_until(20)


#Here's a function that works with negative integers as well, 
def sum_squares_between(x: int) -> int:  #Ensures input and output are integers
   """Calculates the sum of all squared integers from 1 to x. Takes an input integer x and ouputs an integer."""
   sum_squares = 0
   if x < 1:
      for i in range (x, 2):
         sum_squares += i**2
      return sum_squares
   else:
      for i in range(1, x+1):
         sum_squares += i**2
      return sum_squares

sum_squares_between(20)
sum_squares_between(-5)
```

The python library named "os" is a built-in library for dealing with any file on your operating system.
Often, research tasks involve LOTS of files and you need to iterate over them. To show you know how
to do this, use the os.listdir function to answer the following questions. Note that you need to 
write "import os" to import the library into your code before you can use it:

**Part B:** Print out a list of all the files your class root directory. I don't care how many are actually there (in case you've added some yourself) but show me how.

```{python}
#3B Answer

#First, get path to current working directory
current_directory = os.getcwd()

#Because this file is in my "assignment" folder rather than my class root directory, I need to move one level up.
class_root_directory = os.path.dirname(current_directory)

print(f"Listing contents of: {class_root_directory}\n")

#Next, get a list of all entries.
# Use the try ... except method to handle errors so the program doesn't crash
try:
   contents = os.listdir(class_root_directory)
   print(contents)
except OSError as e:
      print(f"Error accessing directory: {e}")
```

**Part C:** Using a FOR loop, iterate over the list from above. Using the function len(), count how many letters there are in the filenames. HINT just like in real life, you may need to google the len() function and see how it work on e.g. strings.

```{python}
#3C Answer

#First answer assumes all entries in the directory are files
for filename in contents:
   len(filename)

#First, get path to current working directory
current_directory = os.getcwd()

#Because this file is in my "assignment" folder rather than my class root directory, I need to move one level up.
class_root_directory = os.path.dirname(current_directory)
print(f"Filename length in {class_root_directory}\n")

#Next, get a list of all entries.
# Use the try ... except method to handle errors so the program doesn't crash
try:
   contents = os.listdir(class_root_directory)
# count how many letters there are in the filenames
   for filename in contents:
      print(len(filename))
except OSError as e:
      print(f"Error accessing directory: {e}")
```

**Part D:** Write a Python program which iterates over the integers from 1 to 50. For multiples of three print "Fizz" instead of the number and for the multiples of five print "Buzz". For numbers which are multiples of both three and five print "FizzBuzz". Hint: look up how to use the modulo operator (which is written as % in python) which would let you test when the remainder of a devision is exactly 0.

Side-note, this is a hilariously over-used question that most software engineers get askedon their first interview for a job.

```{python}
# 3D Answer
for i in range(1,51):
   # Print "Fizzbuzz" if the integer is evenly divisible by both 3 and 5.
   if i % 3 == 0 and i % 5 == 0:
      print("Fizzbuzz")
   # Print "Fizz" if the integer is evenly divisible by 3 only.
   elif i % 3 == 0:
      print("Fizz")
   # Print "Buzz" if the integer is evenly divisible by 5 only.
   elif i % 5 == 0:
      print("Buzz")
   # Print the integer if it is evenly divisible byy neither 3 nor 5.
   else:
      print(i)
```

## Question 4

Create a personal website using GitHub Pages. The website should be just a few pages, including a landing page, a research page, and a contact page. Use Markdown to format the content on your pages. Include links to your GitHub profile and any relevant projects or repositories you have worked on. Once completed, share the link to your GitHub Pages website here. Note, for the pages to actually be hosted online, you will need to create a new repository named <your_github_username>.github.io and push your quarto-rendered markdown files there. See GitHub Pages documentation for more details.

### Hint 1

Organization and customization of your site will be managed by creating a _quarto.yml in your project root with content like below.

project:
  type: website

website:
  title: "Your Name"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - projects.qmd
      - contact.qmd


format:
  html:
    theme: cosmo
    toc: true
    code-copy: true


### Hint 2

Individual pages could be written as, for example, a index.qmd with the following content. 

# Hello, I’m Your Name

Short tagline (e.g., *Applied Economist • Data Scientist*).

- I study ...
- I teach ...
- I build ...


### Hint 3

Call quarto render on the command line in your project root to build the site and generate HTML files.

### Hint 4

To actually host the site, push the rendered HTML files to a GitHub repository named <your_github_username>.github.io. Follow GitHub Pages documentation for details on setting up the repository and enabling GitHub Pages.

Ideally, this should be a public site. However if you would like to remain anonymous, you can just create a private repository and invite me as a collaborator on the repository.



